### ISSUE TITLE
25/07/2024_Coding Convention

### ISSUE THREAD

**Issue by tranducphat204** [MockprojectGr3/MockProject_072024_Gr3_Summary#1]
Team members need to complete the coding convention file.

- FE_REACT [https://docs.google.com/spreadsheets/d/1gtJm-cIF-ThHUD5yYHbWLUdIUpvzaG_a35OTpxK36Sc/edit?gid=31724715#gid=31724715](url)
- BE_SERN and NODE [https://docs.google.com/spreadsheets/d/1gtJm-cIF-ThHUD5yYHbWLUdIUpvzaG_a35OTpxK36Sc/edit?gid=986732702#gid=986732702](url)
- BE_JAVA [https://docs.google.com/spreadsheets/d/1gtJm-cIF-ThHUD5yYHbWLUdIUpvzaG_a35OTpxK36Sc/edit?gid=1139628191#gid=1139628191](url)
- BE_PHP [https://docs.google.com/spreadsheets/d/1gtJm-cIF-ThHUD5yYHbWLUdIUpvzaG_a35OTpxK36Sc/edit?gid=212908248#gid=212908248](url)
- BE_PYTHON [https://docs.google.com/spreadsheets/d/1gtJm-cIF-ThHUD5yYHbWLUdIUpvzaG_a35OTpxK36Sc/edit?gid=1254417487#gid=1254417487](url)

**Comment by tranducphat204** [comment]
REACTJS DONE

**Comment by Gressi-177** [comment]
BE_JAVA DONE

**Comment by AuGoaThree** [comment]
Done

**Comment by tranducphat204** [comment]
SERN DONE
