### ISSUE TITLE
29/07/2024_Learn Git Follow and try push code, merge code on Github

### ISSUE THREAD

**Issue by tranducphat204** [MockprojectGr3/MockProject_072024_Gr3_Summary#10]
ROLE: ALL DEVELOPER.

Link Git Follow: [https://docs.google.com/document/d/1yQ4s5Geum_oCAS5wVon6w_wuYyp1cyvICo6Yc5dXV4g/edit?usp=drive_link](url)

Link Youtube Git follow: [https://www.youtube.com/watch?v=TjztqlGkhjg](url)

**Comment by MockprojectGr3** [comment]
Nguyễn Quốc Dũng - Done

**Comment by Huynh2ne2** [comment]
Đặng Như Huỳnh - Done

**Comment by tranducphat204** [comment]
Trần Đức Phát - Done

**Comment by trongan0409** [comment]
Đoàn Trọng An - Done

**Comment by nguyenvanduc122333** [comment]
Nguyễn Văn Đức - Done

**Comment by ABon485** [comment]
Done

**Comment by phong2k2** [comment]
Lê Nguyễn Bảo Phong - Done

**Comment by nguyenhoai0302** [comment]
Done

**Comment by AuGoaThree** [comment]
done

**Comment by Gressi-177** [comment]
Done

**Comment by PhuongNga0412** [comment]
done
