### ISSUE TITLE
29/07/2024_Learn about error logging and error management on GIT

### ISSUE THREAD

**Issue by tranducphat204** [MockprojectGr3/MockProject_072024_Gr3_Summary#11]
ROLE: TESTER.

Errors log lesson link: [https://docs.google.com/document/d/e/2PACX-1vQKwGmhvN9z7nuiS_Nh5ukmEFLHhlUe74d9p4-EL8vBKsNjCE0uiaUlZp--AdJuje7Eu0eO-g5QBgEv/pub](url)
Errors log lesson on GIT by table link: [https://docs.google.com/document/d/e/2PACX-1vQ5ILaOATxEAAAhHOcgjeI9sJOfjexdI_KVPkJEx_DAPQ4K2ni_cibboBWIIx1UzxqNwqH-d9_6aZCr/pub](url)

Reference file: 
[MockProject_Defect List Sample.xlsx](https://github.com/user-attachments/files/16406386/MockProject_Defect.List.Sample.xlsx)

**Comment by AuGoaThree** [comment]
done
