### ISSUE TITLE
30/07/2024_Draw UI on Figma

### ISSUE THREAD

**Issue by tranducphat204** [MockprojectGr3/MockProject_072024_Gr3_Summary#12]
ROLE: BA + TESTER + DEV.
Please complete on time!

Mission file: [https://docs.google.com/spreadsheets/d/12LpWd_MXvpO2gFP9HCIQ2aZWNs5Br6LazRvvtlAMU4c/edit?gid=0#gid=0](url)

Figma Project Link: [https://www.figma.com/design/QXRGIS1JzhuTejS7FUo37u/Group-3?node-id=0-1&t=OLfBEp2zgYWM1tNv-0](url)

Below is two link template UI:
- Admin role: [https://devforum.info/demo/front-admin-template-devforum-demo384?gidzl=ubVqGV80a7NYI_17znoJS-XBzKBX7i5_yaYZ6UDEm2hsJQ4Tjnd8AVLAe4_gJP1vzHwdJcOdPL45zm6LSG](url)
- User/Customer role: [https://www.guardsecurity.com/](url)

**Comment by Huynh2ne2** [comment]
Done

**Comment by phong2k2** [comment]
Done

**Comment by trongan0409** [comment]
Doan Trong An - Done

**Comment by ThuyNgan015** [comment]
Done

**Comment by tranducphat204** [comment]
Done

**Comment by nguyenvanduc122333** [comment]
Nguyễn Văn Đức - Done

**Comment by NguyenNgan03** [comment]
done
