### ISSUE TITLE
31/07/2024_Test code responsive

### ISSUE THREAD

**Issue by tranducphat204** [MockprojectGr3/MockProject_072024_Gr3_Summary#15]
ROLE: FE.
Please complete on time!!!

Responsive tutorial: [https://hocwebchuan.com/tutorial/responsive/](url)

FE Folder: [https://drive.google.com/drive/folders/1On4YSi3NYZ6Aczl8CBmT6JkhzdVazf8E?usp=drive_link](url)

**Comment by tranducphat204** [comment]
Done

**Comment by ThuyNgan015** [comment]
Done

**Comment by Huynh2ne2** [comment]
Done

**Comment by Huynh2ne2** [comment]
Done

**Comment by Huynh2ne2** [comment]
DONE

**Comment by trongan0409** [comment]
Done
