### ISSUE TITLE
31/07/2024_Learn how to test Web Interfaces using Responsive techniques

### ISSUE THREAD

**Issue by tranducphat204** [MockprojectGr3/MockProject_072024_Gr3_Summary#16]
ROLE: BA + Tester.

Reference documents below: 
- [https://idesign.vn/graphic-design/su-khac-nhau-giua-thiet-ke-web-adaptive-va-responsive-438967.html](url)
- [https://bizmac.com/blog/tin-cong-nghe/su-khac-biet-giua-adaptive-design-va-responsive-design.html](url)
- [https://viblo.asia/p/test-responsive-web-design-nhu-the-nao-OeVKBgkMZkW](url)

Watch this tutorial how to use F12 Devtools on Google Chrome: [https://viblo.asia/p/test-responsive-va-device-specific-viewports-tren-devtools-f12-cua-browser-phan-1-XL6lAvgB5ek](url)

After learning testing techniques, do the exercise Find errors when testing responsive web for the web: [https://www.gdt.gov.vn/wps/portal](url)
BA Folder: [https://drive.google.com/drive/folders/13l5nHLQXrzphV9aPVM3Mu-fc5a748DUS?usp=drive_link](url)
TESTER Folder: [https://drive.google.com/drive/folders/10Yu6WL3sUd8sxYHdgdoE1MZBR67hvmKh?usp=drive_link](url)

**Comment by HLeLeH** [comment]
Lê Thị Hồng Hạnh_done
