### ISSUE TITLE
01/08/2024_Continues Revise FIGMA and Draw

### ISSUE THREAD

**Issue by tranducphat204** [MockprojectGr3/MockProject_072024_Gr3_Summary#17]
ROLE: DEV + BA + TESTER.

Figma Project  Link: [https://www.figma.com/design/QXRGIS1JzhuTejS7FUo37u/Group-3?node-id=0-1&t=8OHdO3mbM0k8QAsv-0](url)

**Comment by tranducphat204** [comment]
Done

**Comment by Huynh2ne2** [comment]
DONE

**Comment by quocdung2603** [comment]
done
