### ISSUE TITLE
01/08/2024_Draw Database Diagram

### ISSUE THREAD

**Issue by tranducphat204** [MockprojectGr3/MockProject_072024_Gr3_Summary#18]
ROLE: DEV + TESTER + BA.

ERD Project Link: [https://app.diagrams.net/#G19Uc9SA10KkYFrxl39y2h9hYk-b00KYl_#%7B%22pageId%22%3A%222_GcQoSe6WFd8bxYhFsl%22%7D](url)

**Comment by tranducphat204** [comment]
Done

**Comment by Huynh2ne2** [comment]
DONE

**Comment by quocdung2603** [comment]
done
