### ISSUE TITLE
02/08/2024_Create Mock Data

### ISSUE THREAD

**Issue by tranducphat204** [MockprojectGr3/MockProject_072024_Gr3_Summary#19]
ROLE: BA + TESTER + DEV.

Requirement: Create at least 20 rows data of each table.

File track task each members : [https://docs.google.com/spreadsheets/d/1U1taXzLkjltKJweXnNmQ5MOUxWh7QBzfIvyMjniyOZ0/edit?gid=0#gid=0](url)

File mock data: [https://docs.google.com/spreadsheets/d/1rU1ic8Lq7bGiHwJxpCiEI_SA5qiC1x94ZgA2d5idP4A/edit?gid=412404746#gid=412404746](url)
ERD project file: [https://app.diagrams.net/#G19Uc9SA10KkYFrxl39y2h9hYk-b00KYl_#%7B%22pageId%22%3A%222_GcQoSe6WFd8bxYhFsl%22%7D](url)

**Comment by trongan0409** [comment]
DoanTrongAn - Done.

**Comment by nguyenhoai0302** [comment]
NguyenHoai - Done

**Comment by ThuyNgan015** [comment]
Done

**Comment by HLeLeH** [comment]
Hạnh Lê- Done

**Comment by tranducphat204** [comment]
Done

**Comment by Huynh2ne2** [comment]
Done

**Comment by Huynh2ne2** [comment]
DONE

**Comment by quocdung2603** [comment]
done

**Comment by ABon485** [comment]
Done

**Comment by longxyn** [comment]
Done

**Comment by Gressi-177** [comment]
Done

**Comment by nguyenvanduc122333** [comment]
done
