### ISSUE TITLE
25/07/2024_How to design with Figma

### ISSUE THREAD

**Issue by tranducphat204** [MockprojectGr3/MockProject_072024_Gr3_Summary#3]
ROLE: DEV, TESTER, BA.

The assigned member will need to learn how to design on Figma.
[https://www.figma.com/design/QXRGIS1JzhuTejS7FUo37u/Group-3?node-id=0-1&t=jncvP33kGnKoKFIA-0](url)

**Comment by Huynh2ne2** [comment]
Done

**Comment by Gressi-177** [comment]
Done

**Comment by trongan0409** [comment]
done
