### ISSUE TITLE
25/07/2024_Unified one Framework

### ISSUE THREAD

**Issue by tranducphat204** [MockprojectGr3/MockProject_072024_Gr3_Summary#5]
ROLE: DEV BE + FE

The assigned member will need to complete.

[https://docs.google.com/spreadsheets/d/1gtJm-cIF-ThHUD5yYHbWLUdIUpvzaG_a35OTpxK36Sc/edit?usp=drive_link](url)

**Comment by tranducphat204** [comment]
FE DONE

**Comment by tranducphat204** [comment]
BE DONE

**Comment by trongan0409** [comment]
SERN done
