### ISSUE TITLE
26/07/2024_Choose template and code login.

### ISSUE THREAD

**Issue by tranducphat204** [MockprojectGr3/MockProject_072024_Gr3_Summary#6]
ROLE: DEV + TESTER + BA.

Link template: [https://external.asisonline.org/eWeb/DynamicPage.aspx?WebCode=LoginRequired&expires=yes&Site=asis&URL_success=https%3a%2f%2fwww.asisonline.org%2f](url)

Link folder FE: [https://drive.google.com/drive/folders/1dp39T6V6znxviXNGbrxWAlHldu5UqYhh?usp=drive_link](url)
Link folder BE: [https://drive.google.com/drive/folders/1v0giP_u_CxGUsN0IPeUsxpRR0sCngkqW?usp=drive_link](url)

**Comment by tranducphat204** [comment]
Done

**Comment by Huynh2ne2** [comment]
DONE

**Comment by Gressi-177** [comment]
Done

**Comment by ThuyNgan015** [comment]
Done

**Comment by AuGoaThree** [comment]
DONE

**Comment by NguyenNgan03** [comment]
done

**Comment by phong2k2** [comment]
done

**Comment by ABon485** [comment]
Done

**Comment by PhuongNga0412** [comment]
Done

**Comment by nguyenhoai0302** [comment]
Done

**Comment by trongan0409** [comment]
done
