### ISSUE TITLE
26/07/2024_Research and write testcase like template.

### ISSUE THREAD

**Issue by tranducphat204** [MockprojectGr3/MockProject_072024_Gr3_Summary#7]
ROLE: TESTER.

File template: 
[MockProject_Test Case_Sample.xlsx](https://github.com/user-attachments/files/16385602/MockProject_Test.Case_Sample.xlsx)

Folder: [https://drive.google.com/drive/folders/12XbTSsOJ_JbOKV3TrCbg6kS8BXcldbZO?usp=drive_link](url)

**Comment by HLeLeH** [comment]
Complete
