### ISSUE TITLE
26/07/2024_Software Business Research

### ISSUE THREAD

**Issue by tranducphat204** [MockprojectGr3/MockProject_072024_Gr3_Summary#8]
ROLE: BA.

File: 
[Cho thue ve si_EN.zip](https://github.com/user-attachments/files/16385593/Cho.thue.ve.si_EN.zip)

Folder: https://drive.google.com/drive/folders/1muyPvAAjmjFyKJXDsI4Cj-uBbzJ9KjrL?usp=drive_link

**Comment by NThuy-4** [comment]
Done
