### ISSUE TITLE
29/07/2024_Proceed to sketch the screen for the system

### ISSUE THREAD

**Issue by tranducphat204** [MockprojectGr3/MockProject_072024_Gr3_Summary#9]
ROLE: BA

Steps by step: 
- Step 1: List the names of all the screens that will be in the software.
- Step 2: For each screen, list the information (fields), tables (if any) and links or buttons that will be in that screen.
- Step 3: Save the information done in Step 1 and Step 2 into a docx file (to submit to Mentor the next day along with the FIGMA screen).
- Step 4: Sketch the screens listed in the above steps on paper (draft, for speed) to send to the project team the next day.

Link Figma: [https://www.figma.com/design/QXRGIS1JzhuTejS7FUo37u/Group-3?node-id=0-1&t=YXiyfmCXV7OF79JT-0](url)

**Comment by NThuy-4** [comment]
Done
