### ISSUE TITLE
[Bug]Func_Trang chủ_Kiểm tra nút "Contact Us"_Không chuyển đến trang Contact Us sau khi click

### ISSUE THREAD

**Issue by khanh2810** [MockprojectGr3/MockProject_072024_Gr3_Summary#99]
Actual output: Khi người dùng nhấp vào nút "Contact Us" trên trang chủ, trang web không thực hiện điều hướng,
Expected output:
Khi người dùng nhấp vào nút "Contact Us" trên trang chủ, trang web sẽ điều hướng người dùng đến trang "Contact Us"

test case id 2

**Comment by Huynh2ne2** [comment]
DONE
